name: Run_unit_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Run unit tests on PR or push in main
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
        
      - name: Run gradle tests
        env: 
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew test --stacktrace
        working-directory: ./Filmograf