name: Test_build_send_aab_release

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
    
jobs:
  build_aab:
    env:
      FILMOGRAF_KEYSTORE_PASSWORD: ${{ secrets.FILMOGRAF_KEYSTORE_PASSWORD }}
      FILMOGRAF_RELEASE_SIGN_KEY_ALIAS: ${{ secrets.FILMOGRAF_RELEASE_SIGN_KEY_ALIAS }}
      FILMOGRAF_RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.FILMOGRAF_RELEASE_SIGN_KEY_PASSWORD }}
      
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Checkout keystore repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.FILMOGRAF_KEYSTORE_REPOSITORY }}
          ref: 'main'
          token: ${{ secrets.FILMOGRAF_KEYSTORE_ACCESS_TOKEN }}
          path: ./Filmograf/app/keystore

      - name: Run tests and build release artifacts
        env: 
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          chmod +x gradlew
          ./gradlew test
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease
        working-directory: ./Filmograf

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: Filmograf/app/build/outputs/bundle/release/app-release.aab
          
  send_aab:
    name: Update release RuStore
    needs: build_aab
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download AAB file
        uses: actions/download-artifact@v2
        with:
          name: app-release.aab
      
      - name: Send AAB to RuStore
        run: |
          curl --location --request POST "${{ secrets.RUSTORE_URL }}" --verbose \
          --header "Public-Token: ${{ secrets.RUSTORE_API_KEY }}" \
          --header "Content-Type: multipart/form-data" \
          --form "file=@app-release.aab"