# This is a basic workflow to help you get started with Actions

name: Run_unit_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    name: Run unit tests on PR or push in main
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: ./Filmograf
        
      - name: Run gradle tests
        run: ./gradlew test --stacktrace
        working-directory: ./Filmograf